include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_use_package_imports
    - avoid_print
    - prefer_const_constructors
    - prefer_final_locals
    - sort_child_properties_last
    - use_key_in_widget_constructors
